repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: ^CHANGELOG.md
    -   id: end-of-file-fixer
        exclude: ^CHANGELOG.md
    -   id: trailing-whitespace
        exclude: ^CHANGELOG.md
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
        -   id: black
            exclude: ^CHANGELOG.md
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
        -   id: mypy
            exclude: isi_test_task/isi_test_task/settings.py
            additional_dependencies:
            - django-stubs
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        -   id: isort
            exclude: ^CHANGELOG.md
            files: "^isi_test_task/.*\\.py$"
            args: [--settings-path=pyproject.toml]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
        -   id: commitizen
            exclude: ^CHANGELOG.md
            stages: [commit-msg]
