repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: ^CHANGELOG.md
    -   id: end-of-file-fixer
        exclude: ^CHANGELOG.md
    -   id: trailing-whitespace
        exclude: ^CHANGELOG.md
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
        -   id: black
            exclude: ^CHANGELOG.md
-   repo: https://github.com/life4/flakehell
    rev: v.0.7.1
    hooks:
        -   id: flakehell
            name: flakehell
            language: system
            types: ["file", "text"]
            files: \.(ipynb|md|py|rst|yaml|yml)$
            entry: poetry run flakehell lint
            require_serial: True
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
        -   id: isort
            exclude: ^CHANGELOG.md
            files: "^isi_test_task/.*\\.py$"
            args: [--settings-path=pyproject.toml]
-   repo: local
    hooks:
       -    id: django-test
            name: django-test
            entry: python isi_test_task/manage.py test
            always_run: true
            pass_filenames: false
            language: system
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.19.0
    hooks:
        -   id: commitizen
            exclude: ^CHANGELOG.md
            stages: [commit-msg]
